config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#new' , as: 'home'

  resources :books, only: [:new, :create, :edit, :index, :show, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :index ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true,uniqueness: true, length: {in: 2..20}
  validates :introduction,  length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!,except: [:top, :new ]

before_action :configure_permitted_parameters, if: :devise_controller?



  def after_sign_in_path_for(resource)

    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:password])

  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
   @book = Book.new

  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to  book_path(@book.id)
    else
      flash.now[:alert] = 'You have created book error.'
      render :index
    end

  end

  def index
    @books = Book.all
    @users = User.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new

  end
  def edit
     @user = User.find(params[:id])
     @book = Book.find(params[:id])
     @books = Book.all
     @book_new = Book.new
    if @book.user == current_user
            render "edit"
    else
            redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    flash.now[:alert] = 'You have updated book error.'
    render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end

private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# before_action :ensure_current_user, {only: [:edit, :update]}
# def ensure_current_user
#   if @current_user.id != params[:id].to_i
#     redirect_to("/users")
#   end
# end
  def show

  @user = User.find(params[:id])
  @books = Book.all
  @user_books = @user.books
  @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
      if @user == current_user
        render "edit"
      else
        redirect_to user_path(current_user.id)
      end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    flash.now[:alert] = 'You have updated user error.'
    render :edit
    end
  end

 private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

<% if book.errors.any? %>
  <%= book.errors.count %>errors prohibited this user from being saved:
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h2>User info</h2>
<div class="profile-container">
   <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th class="profile-name"><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th class="profile-introduction"><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">

 <%= link_to  edit_user_path(user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog', method: :get do%><% end %>

</div>

<h2 class="mt-3">New book</h2>

<%= form_with model:book, local: true do |f| %>
<div class="form-group">
  <label for="book_title">Title</label>
  <%= f.text_field :title, class: 'form-control'  %>
</div>
<div class="form-group">
  <label for="book_opinion">Option</label>
  <%= f.text_area :body, class: 'form-control book_body' %>
</div>
<div class="form-group">
  <%= f.submit 'Create Book', class: 'btn btn-success' %>
<% end %>
</div>
    </div>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title ,class: "form-control book_title"%>
        </div>
        <div class="form-group">
          <label for="book_opinion">Option</label>
          <%= f.text_area :body ,class: "form-control book_body"%>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book' ,class: "btn btn-success" %>
        </div>
        <% end %>
        <%= link_to book_path(@book.id) do %>Show<% end %>
        &nbsp;|&nbsp;
        <%= link_to books_path do %>Back<% end %>
    </div>
  </div>
</div>
</div>

app/views/books/index.html.erb
<%= render 'books/sideber', user: current_user, book: @book %>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody><% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.id) do %>
        <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg" , size: "40x40"%>
      <% end %>
      </td>
      <td>
        <%= link_to book_path(book.id) do %><%= book.title %><% end %>
      </td>
      <td>
        <%= book.body %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>


</div>

app/views/books/show.html.erb
<%= render 'books/sideber', user: @book.user, book: @book_new %>

<div class="col-md-8 offset-md-1">

<h2>Book detail</h2>
<table class="table">
  <tbody>
    <tr>
      <td>
        <%= attachment_image_tag @book.user, :profile_image, fallback: "no_image.jpg" , size: "40x40"%>
        <%= link_to user_path(@book.user.id) do %>
        <br><%= @book.user.name %>
        <% end %>
      </td>
      <td>
        <%= link_to book_path(@book.id) do %>
        <%= @book.title %>
        <% end %>
      </td>
      <td>
        <%= @book.body %>
      </td>
      <td>
        <% if @book.user == current_user %>
        <%= link_to "Edit", edit_book_path(@book), class: 'btn btn-sm btn-success' %>
      </td>
      <td>
        <%= link_to "Destroy", book_path(@book),class: 'btn btn-sm btn-danger', method: :delete, "data-confirm" => "本当に消しますか？" %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
</div></div>

app/views/homes/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions ,and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header >
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <%= link_to root_path ,class: 'navbar-brand',  method: :get do%> <span>Bookers</span>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

         <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: "fas fa-home nav-link text-light", method: :get do%>&nbsp;Home
            <% end %></li>
            <li>
              <%= link_to  users_path, class: "fas fa-users nav-link text-light", method: :get do%>&nbsp;Users
            <% end %></li>
            <li>
              <%= link_to  books_path, class: "fas fa-book-open nav-link text-light", method: :get do%>&nbsp;Books
            <% end %> </li>
            <li>
              <%= link_to  destroy_user_session_path , class: "fas fa-sign-out-alt nav-link text-light", method: :delete do%>&nbsp;logout
            <% end %></li>

            <% else %>
            <li>
               <%= link_to  root_path ,class: "fas fa-home nav-link text-light", method: :get do%>&nbsp;Home
            <% end %></li>
            <li>
               <%= link_to  home_path ,class: "fas fa-link nav-link text-light", method: :get do%>&nbsp;About
            <% end %></li>
            <li>
              <%= link_to  new_user_registration_path ,class: "fas fa-user-plus nav-link text-light", method: :get do%>&nbsp;sign up
            <% end %></li>
            <li>
              <%= link_to new_user_session_path ,class: "fas fa-sign-in-alt nav-link text-light", method: :get do%>&nbsp;login
            <% end %></li>

          <% end %>

        </ul>
        </div>
      </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
    <p class="text-<%= key %>">
    <%= value %>
    <% end %>
    </p>
    <%= yield %>
    </main>
</body>
    <footer>
      <div class="conrainer mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infrarop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this user from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label for="user_Name">Name</label>
        <%= f.text_field :name, autofocus: true, id:"user_Name", class: "form-control name" %>
      </div>
      <div class="form-group">
        <label for="user_image">Image</label>
         <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image"%>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, autofocus: true, class: "form-control introduction" %>
      </div>
      <div class="form-group">
          <%= f.submit "Update User" ,class: "btn btn-secondary"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'books/sideber', user: current_user, book: @book %>


    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody><% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to user_path(user.id) do %>Show<% end %>
              </td>
            </tr><% end %>
          </tbody>
        </table>
    </div>
  </div>

app/views/users/show.html.erb
<%= render 'books/sideber', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody><% @user_books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(@user.id) do %>
        <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:"40x40" %>
      <% end %>
      </td>
      <td>
        <%= link_to book_path(book.id) do %><%= book.title %><% end %>
      </td>
      <td>
        <%= book.body %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>


</div>